#!/bin/bash


## Clear Cache And Temp Files
   pkg autoremove &>/dev/null
   pkg remove &>/dev/null
   pkg clear &>/dev/null
   
 ## Continue
pkg install ncurses-utils -y &>/dev/null
pkg install wget -y &>/dev/null
cd /data/data/com.termux/files/
wget -q https://github.com/Boxvidra/Boxvidra-Project/releases/download/Native-Glibc/termux-style.tar.xz
tar -xf termux-style.tar.xz
rm termux-style.tar.xz
cd
clear

. $PREFIX/glibc/opt/termux-style/termux-style
. $PREFIX/glibc/opt/scripts/dialogs
. $PREFIX/glibc/opt/scripts/configs
apply-termux-style 

## Completed Version Notice 
clear
mkdir -p "/data/data/com.termux/files/usr/bin/notice"
if [ ! -e "/data/data/com.termux/files/usr/bin/notice/notice1_shown" ]; then
	touch "/data/data/com.termux/files/usr/bin/notice/notice1_shown"
	dialog_msgbox "Boxvidra Project - Emulator (Native)" \
		"Notice From Boxvidra Developers Team \nYou're About To Install Boxvidra Emulator (Native, v1.1.0) Version, Make Sure That You Have 5 GB As A Free Space And 2 GB As A Free Internet, Thank you."
fi
##

clear
echo "Installing Required Aackages And Updating, Upgrading Termux Packages . . ."
echo -e "\n"
termux-setup-storage
pkg update -y
termux-change-repo
pkg upgrade -y
pkg install wget -y
pkg install git -y
pkg install hashdeep -y
pkg install x11-repo
sleep 2
clear

# Setting Up The Storage
echo -e "\e[33m[i] Setting up storage permissions..\e[0m"
yes | termux-setup-storage &>/dev/null
sleep 2
clear
while true; do
    if [ -d ~/storage/shared ]; then
        break
    else
        echo -e "\e[31m[ERR] Storage permission denied\e[0m"
    fi
done

# Installing Termux-Am
clear
sleep 2
echo -e "\e[36m[+] Installing Termux-am\e[0m"
pkg install termux-am -y &>/dev/null
echo -e "\e[32m[✓] Termux-am Installed Successfully\e[0m"
echo -e "\n"
clear

## Clear Cache And Temp Files
   pkg autoremove &>/dev/null
   pkg remove &>/dev/null
   pkg clear &>/dev/null

# Installing The Glibc
    dialog_menu "\Z6Select A Glibc To Install" "" \
    "1" "\Z6Install Box64 And Box86 Glibc \Z5(v1.0)" \
    "2" "\Z6Install Wow64 Glibc \Z5(v1.0)" \

case $? in
1)
    clear
    echo -e "\e[36m[+] Installing Boxvidra Emulator Native (Box64 And Box86) Glibc\e[0m"
    wget -q --show-progress -O /data/data/com.termux/files/glibc.box64-86.tar.xz https://github.com/Boxvidra/Boxvidra-Project/releases/download/Native-Glibc/glibc.box64-86.tar.xz
    sleep 2
    echo -e "\e[33m[i] Extracting Box64 And Box86 Glibc . . .\e[0m"
    tar -xf /data/data/com.termux/files/glibc.box64-86.tar.xz -C /data/data/com.termux/files/
    sleep 2
    echo -e "\e[32m[✓] Boxvidra Emulator Native (Box64 And Box86 Glibc-Divided) Installed Successfully.\e[0m"
    sleep 2
    wget -q --show-progress -O /data/data/com.termux/files/usr/glibc/glibc.box64-86.opt.tar.xz https://github.com/Boxvidra/Boxvidra-Project/releases/download/Native-Glibc/glibc.box64-86.opt.tar.xz
    sleep 2
    echo -e "\e[33m[i] Extracting Box64 And Box86 Glibc (Opt) . . .\e[0m"
    tar -xf /data/data/com.termux/files/usr/glibc/glibc.box64-86.opt.tar.xz -C /data/data/com.termux/files/usr/glibc/
    sleep 2
    echo -e "\e[32m[✓] Boxvidra Emulator Native (Box64 And Box86 Opt) Installed Successfully.\e[0m"
    sleep 2
    wget -q --show-progress -O /data/data/com.termux/files/usr/glibc/opt/glibc.box64-86.scripts.tar.xz https://github.com/Boxvidra/Boxvidra-Project/releases/download/Native-Glibc/glibc.box64-86.scripts.tar.xz
    sleep 2
    echo -e "\e[33m[i] Setting Up Box64 And Box86 Glibc Scripts And Files . . .\e[0m"
    tar -xf /data/data/com.termux/files/usr/glibc/opt/glibc.box64-86.scripts.tar.xz -C /data/data/com.termux/files/usr/glibc/opt/
    sleep 2
    mv /data/data/com.termux/files/usr/glibc/opt/scripts/boxvidra /data/data/com.termux/files/usr/bin
    mv /data/data/com.termux/files/usr/glibc/opt/scripts/boxvidra-native /data/data/com.termux/files/usr/bin
    mv /data/data/com.termux/files/usr/glibc/opt/scripts/vidra /data/data/com.termux/files/usr/bin
    chmod +x /data/data/com.termux/files/usr/glibc/opt/scripts/*
    chmod +x /data/data/com.termux/files/usr/glibc/opt/scripts/settings-manage/*
    chmod +x /data/data/com.termux/files/usr/glibc/opt/scripts/important-scripts/*
    chmod +x /data/data/com.termux/files/usr/glibc/opt/scripts/start-modes/*
    chmod 777 /data/data/com.termux/files/usr/bin/boxvidra
    chmod 777 /data/data/com.termux/files/usr/bin/boxvidra-native
    chmod 777 /data/data/com.termux/files/usr/bin/vidra
    chmod +x /data/data/com.termux/files/usr/bin/*
    rm /data/data/com.termux/files/glibc.box64-86.tar.xz
    rm /data/data/com.termux/files/usr/glibc/opt/glibc.box64-86.scripts.tar.xz
    rm /data/data/com.termux/files/usr/glibc/glibc.box64-86.opt.tar.xz    
    sleep 3
    echo -e "\n"
    clear
## Installed Successfully Box64 And Box86
    mkdir -p "/data/data/com.termux/files/usr/bin/notice2"
    if [ ! -e "/data/data/com.termux/files/usr/bin/notice2/notice2_shown" ]; then
	touch "/data/data/com.termux/files/usr/bin/notice2/notice2_shown"
	dialog_msgbox "Boxvidra Emulator (Native)" \
		"Box64 And Box86 Glibc Installed Successfully"
fi
    sleep 3
    ;;
2)
    clear
    echo -e "\e[36m[+] Installing Boxvidra Emulator Native (Wow64) Glibc\e[0m"
    wget -q --show-progress -O /data/data/com.termux/files/glibc.wow64.tar.xz https://github.com/Boxvidra/Boxvidra-Project/releases/download/Native-Glibc/glibc.wow64.tar.xz
    sleep 2
    echo -e "\e[33m[i] Extracting Wow64 Glibc . . .\e[0m"
    tar -xf /data/data/com.termux/files/glibc.wow64.tar.xz -C /data/data/com.termux/files/
    sleep 2
    echo -e "\e[32m[✓] Boxvidra Emulator Native (Wow64 Glibc-Divided) Installed Successfully.\e[0m"
    sleep 2
    wget -q --show-progress -O /data/data/com.termux/files/usr/glibc/glibc.wow64.opt.tar.xz https://github.com/Boxvidra/Boxvidra-Project/releases/download/Native-Glibc/glibc.wow64.opt.tar.xz
    sleep 2
    echo -e "\e[33m[i] Extracting wow64 Glibc (Opt) . . .\e[0m"
    tar -xf /data/data/com.termux/files/usr/glibc/glibc.wow64.opt.tar.xz -C /data/data/com.termux/files/usr/glibc/
    sleep 2
    echo -e "\e[32m[✓] Boxvidra Emulator Native (Wow64 Opt) Installed Successfully.\e[0m"
    sleep 2
    wget -q --show-progress -O /data/data/com.termux/files/usr/glibc/opt/glibc.wow64.scripts.tar.xz https://github.com/Boxvidra/Boxvidra-Project/releases/download/Native-Glibc/glibc.wow64.scripts.tar.xz
    sleep 2
    echo -e "\e[33m[i] Setting Up Wow64 Glibc (Scripts) . . .\e[0m"
    tar -xf /data/data/com.termux/files/usr/glibc/opt/glibc.wow64.scripts.tar.xz -C /data/data/com.termux/files/usr/glibc/opt/
    sleep 2
    mv /data/data/com.termux/files/usr/glibc/opt/scripts/boxvidra /data/data/com.termux/files/usr/bin
    mv /data/data/com.termux/files/usr/glibc/opt/scripts/boxvidra-native /data/data/com.termux/files/usr/bin
    mv /data/data/com.termux/files/usr/glibc/opt/scripts/vidra /data/data/com.termux/files/usr/bin
    chmod +x /data/data/com.termux/files/usr/glibc/opt/scripts/*
    chmod +x /data/data/com.termux/files/usr/glibc/opt/scripts/settings-manage/*
    chmod +x /data/data/com.termux/files/usr/glibc/opt/scripts/important-scripts/*
    chmod +x /data/data/com.termux/files/usr/glibc/opt/scripts/start-modes/*
    chmod 777 /data/data/com.termux/files/usr/bin/boxvidra
    chmod 777 /data/data/com.termux/files/usr/bin/boxvidra-native
    chmod 777 /data/data/com.termux/files/usr/bin/vidra
    chmod +x /data/data/com.termux/files/usr/bin/*
    rm /data/data/com.termux/files/glibc.wow64.tar.xz
    rm /data/data/com.termux/files/usr/glibc/opt/glibc.wow64.scripts.tar.xz
    rm /data/data/com.termux/files/usr/glibc/glibc.wow64.opt.tar.xz    
    sleep 3
    echo -e "\n"
    clear
## Installed Successfully Wow64
    mkdir -p "/data/data/com.termux/files/usr/bin/notice2"
    if [ ! -e "/data/data/com.termux/files/usr/bin/notice2/notice2_shown" ]; then
	touch "/data/data/com.termux/files/usr/bin/notice2/notice2_shown"
	dialog_msgbox "Boxvidra Emulator (Native)" \
		"Wow64 Glibc Installed Successfully"
fi
    sleep 3
    ;;
*)
    return 1
    ;;
esac

## Clear Cache And Temp Files
   pkg autoremove &>/dev/null
   pkg remove &>/dev/null
   pkg clear &>/dev/null

## Packages Installation Notice 
clear
mkdir -p "/data/data/com.termux/files/usr/bin/notice56"
if [ ! -e "/data/data/com.termux/files/usr/bin/notice/notice56_shown" ]; then
	touch "/data/data/com.termux/files/usr/bin/notice/notice56_shown"
	dialog_msgbox "Boxvidra Project - Emulator (Native)" \
		"Progress Notice \nYou're About To Install Boxvidra Emulator (Native) Packages, Applications, Important Tools."
fi
##

# Continue
sleep 2
clear
echo -e "\e[32m[+] Installing Termux Packages . . .\e[0m"
apt-get clean -y
apt-get update -y
apt-get upgrade -y
pkg install wget -y
pkg install root-repo -y
apt install android-tools -y
apt-get -y --with-new-pkgs -o Dpkg::Options::="--force-confdef" upgrade
echo -e "\e[32m[✓] Termux packages Installed Successfully.\e[0m"
echo -e "\n"
clear

echo -e "\e[36m[+] Installing Termux X11 packages . . .\e[0m"
pkg install x11-repo -y &>/dev/null
pkg install termux-x11-nightly -y &>/dev/null
echo -e "\e[32m[✓] Termux X11 Packages Installed Successfully.\e[0m"
echo -e "\n"

echo -e "\e[36m[+] Installing Boxvidra Emulator Packages . . .\e[0m"
pkg install tur-repo -y &>/dev/null
pkg install xwayland -y &>/dev/null
pkg install xorg-xrandr -y &>/dev/null
pkg install p7zip -y &>/dev/null
pkg install patchelf -y &>/dev/null
pkg install ncurses-utils -y &>/dev/null
pkg install hashdeep -y &>/dev/null
pkg install mesa-zink virglrenderer-mesa-zink vulkan-loader-android virglrenderer-android -y &>/dev/null
pkg install python-tkinter -y &>/dev/null
pkg install qt5-qtbase -y &>/dev/null
echo -e "\e[32m[✓] Boxvidra Emulator Packages Installed Successfully.\e[0m"
echo -e "\n"
sleep 2
clear
sleep 3

echo -e "\e[36m[+] Installing Xfce4, Plugins and Tools . . .\e[0m"
echo -e "\n"
pkg install xfce4 -y
apt install xfce4-whiskermenu-plugin -y
apt install xfce4-screenshooter -y
apt install xfce4-taskmanager -y
apt install xfce4-docklike-plugin -y
apt install matchbox-keyboard -y
apt update -y
apt upgrade -y
echo -e "\e[32m[✓] Xfce4, Plugins, Tools, Packages, Installed Successfully.\e[0m"
echo -e "\n"
sleep 3
clear

echo -e "\e[36m[+] Installing Boxvidra Emulator Programs, Browsers, Etc . . .\e[0m"
echo -e "\n"
pkg install firefox -y
pkg install vlc -y
pkg install vlc-qt -y
apt install ristretto -y
echo -e "\n"
echo -e "\e[32m[✓] Boxvidra Emulator Programs, Browsers, Other Applications Installed Successfully.\e[0m"
sleep 3
clear

## Clear Cache And Temp Files
   pkg autoremove &>/dev/null
   pkg remove &>/dev/null
   pkg clear &>/dev/null

## Make A Desktop Folder
[ ! -d ~/Desktop ] && mkdir ~/Desktop

# Configuration apps menu
dialog_menu "\Z6Boxvidra Emulator - Configuration Apps Settings" "" \
"1" "\Z6Boxvidra Configuration Application \Z5(Completed, Recommended For Box64-86 And Wow64 Glibc)" \
"2" "\Z6WineXF Manager Application \Z5(non-Completed, Recommended For Wow64 Glibc)"

case $? in
  1)
    # If option 1 is selected, show the submenu again
    dialog_menu "\Z6Boxvidra Emulator - Configuration Modes" "" \
    "1" "\Z6Boxvidra Configuration Application Light \Z5(Mode)" \
    "2" "\Z6Boxvidra Configuration Application Dark \Z5(Mode)"

    case $? in
      1)
        # Ensure files are deleted only if they exist
        cp /data/data/com.termux/files/usr/glibc/opt/libs/app/boxvidra-cfg/Desktop/* ~/Desktop
        cp /data/data/com.termux/files/usr/glibc/opt/libs/app/modes/light/boxvidra-cfg.py /data/data/com.termux/files/usr/glibc/opt/libs/app/'boxvidra cfg'/
        ;;
      2)
        cp /data/data/com.termux/files/usr/glibc/opt/libs/app/boxvidra-cfg/Desktop/* ~/Desktop
        cp /data/data/com.termux/files/usr/glibc/opt/libs/app/modes/dark/boxvidra-cfg.py /data/data/com.termux/files/usr/glibc/opt/libs/app/'boxvidra cfg'/
        ;;
    esac
    ;;
  2)
    cp /data/data/com.termux/files/usr/glibc/opt/libs/winexf-manager/* ~/Desktop
    ;;
esac

## Customization Files Installation Notice 
clear
mkdir -p "/data/data/com.termux/files/usr/bin/notice55"
if [ ! -e "/data/data/com.termux/files/usr/bin/notice/notice55_shown" ]; then
	touch "/data/data/com.termux/files/usr/bin/notice/notice55_shown"
	dialog_msgbox "Boxvidra Project - Emulator (Native)" \
		"Progress Notice \nThe Main Files Installation Process Is Completed Successfully, Now You're About To Install The Customization Files, Themes, Etc.."
fi
##

# Install A Theme
dialog_menu "\Z6Select A Theme Pack" "" \
"1" "\Z6Windows 10 Theme Pack \Z5(New, Special, Recommended)" \
"2" "\Z6Windows 95 To Windows 7 Theme Pack \Z5(Old, Nostalgia)"
case $? in
1)
    dialog_menu "\Z6Select A Theme To Install" "" \
    "1" "\Z6Windows 10 Light Mode Theme \Z5(New, Recommended)" \
    "2" "\Z6Windows 10 Dark Mode Theme \Z5(Recommended)" \
    "3" "\Z6Windows 10 Red Mode Theme \Z5(New, Recommended As A Gaming Theme)" \
    "4" "\Z6Windows 10 Purple Mode Theme \Z5(New, Recommended)" \
    "5" "\Z6Windows 10 Green Mode Theme \Z5(New)" \
    "6" "\Z6Windows 10 Yellow Mode Theme \Z5(New)"
    case $? in
        1)
            echo -n "Installing Windows 10 Light Mode Theme . . ."
            wget -q --show-progress -O Windows.10.Theme.Pack.tar.xz https://github.com/Boxvidra/Boxvidra-Project/releases/download/Native-Themes/Windows.10.Theme.Pack.tar.xz
            tar -xf Windows.10.Theme.Pack.tar.xz
            cd 'Windows 10 Theme Pack'
            cp -r .icons /data/data/com.termux/files/home/
            cp -r .themes /data/data/com.termux/files/home/
            cp -r 'Accessories And Backgrounds' /data/data/com.termux/files/home
            cp Programs/* ~/Desktop
            cp -r 'Configs (Light And Dark, Red And Purple, Green And Yellow Modes)' /data/data/com.termux/files/usr/share
            tar -xf /data/data/com.termux/files/usr/share/'Configs (Light And Dark, Red And Purple, Green And Yellow Modes)'/'Light Mode Config'/.config.tar.xz -C /data/data/com.termux/files/home
            cp Windows-10-Icons.tar.xz /data/data/com.termux/files/usr/share/icons
            tar -xf /data/data/com.termux/files/usr/share/icons/Windows-10-Icons.tar.xz -C /data/data/com.termux/files/usr/share/icons
            cd
            chmod 777 -R 'Windows 10 Theme Pack'
            rm -r 'Windows 10 Theme Pack'
            rm Windows.10.Theme.Pack.tar.xz
            rm /data/data/com.termux/files/usr/share/icons/Windows-10-Icons.tar.xz
            clear
            ## Installed Successfully Theme
            mkdir -p "/data/data/com.termux/files/usr/bin/notice4"
            if [ ! -e "/data/data/com.termux/files/usr/bin/notice4/notice4_shown" ]; then
                touch "/data/data/com.termux/files/usr/bin/notice4/notice4_shown"
                dialog_msgbox "Boxvidra Emulator Native" \
                "Windows 10 Mode Theme (Light) Installed Successfully."
            fi
            ;;
        2)
            echo -n "Installing Windows 10 Dark Mode Theme . . ."
            wget -q --show-progress -O Windows.10.Theme.Pack.tar.xz https://github.com/Boxvidra/Boxvidra-Project/releases/download/Native-Themes/Windows.10.Theme.Pack.tar.xz
            tar -xf Windows.10.Theme.Pack.tar.xz
            cd 'Windows 10 Theme Pack'
            cp -r .icons /data/data/com.termux/files/home/
            cp -r .themes /data/data/com.termux/files/home/
            cp -r 'Accessories And Backgrounds' /data/data/com.termux/files/home
            cp Programs/* ~/Desktop
            cp -r 'Configs (Light And Dark, Red And Purple, Green And Yellow Modes)' /data/data/com.termux/files/usr/share
            tar -xf /data/data/com.termux/files/usr/share/'Configs (Light And Dark, Red And Purple, Green And Yellow Modes)'/'Dark Mode Config'/.config.tar.xz -C /data/data/com.termux/files/home
            cp Windows-10-Icons.tar.xz /data/data/com.termux/files/usr/share/icons
            tar -xf /data/data/com.termux/files/usr/share/icons/Windows-10-Icons.tar.xz -C /data/data/com.termux/files/usr/share/icons
            cd
            chmod 777 -R 'Windows 10 Theme Pack'
            rm -r 'Windows 10 Theme Pack'
            rm Windows.10.Theme.Pack.tar.xz
            rm /data/data/com.termux/files/usr/share/icons/Windows-10-Icons.tar.xz
            clear
            ## Installed Successfully Theme
            mkdir -p "/data/data/com.termux/files/usr/bin/notice4"
            if [ ! -e "/data/data/com.termux/files/usr/bin/notice4/notice4_shown" ]; then
                touch "/data/data/com.termux/files/usr/bin/notice4/notice4_shown"
                dialog_msgbox "Boxvidra Emulator Native" \
                "Windows 10 Mode Theme (Dark) Installed Successfully."
            fi
            ;;
        3)
            echo -n "Installing Windows 10 Red Mode Theme . . ."
            wget -q --show-progress -O Windows.10.Theme.Pack.tar.xz https://github.com/Boxvidra/Boxvidra-Project/releases/download/Native-Themes/Windows.10.Theme.Pack.tar.xz
            tar -xf Windows.10.Theme.Pack.tar.xz
            cd 'Windows 10 Theme Pack'
            cp -r .icons /data/data/com.termux/files/home/
            cp -r .themes /data/data/com.termux/files/home/
            cp -r 'Accessories And Backgrounds' /data/data/com.termux/files/home
            cp Programs/* ~/Desktop
            cp -r 'Configs (Light And Dark, Red And Purple, Green And Yellow Modes)' /data/data/com.termux/files/usr/share
            tar -xf /data/data/com.termux/files/usr/share/'Configs (Light And Dark, Red And Purple, Green And Yellow Modes)'/'Red Mode Config'/.config.tar.xz -C /data/data/com.termux/files/home
            cp Windows-10-Icons.tar.xz /data/data/com.termux/files/usr/share/icons
            tar -xf /data/data/com.termux/files/usr/share/icons/Windows-10-Icons.tar.xz -C /data/data/com.termux/files/usr/share/icons
            cd
            chmod 777 -R 'Windows 10 Theme Pack'
            rm -r 'Windows 10 Theme Pack'
            rm Windows.10.Theme.Pack.tar.xz
            rm /data/data/com.termux/files/usr/share/icons/Windows-10-Icons.tar.xz
            clear
            ## Installed Successfully Theme
            mkdir -p "/data/data/com.termux/files/usr/bin/notice4"
            if [ ! -e "/data/data/com.termux/files/usr/bin/notice4/notice4_shown" ]; then
                touch "/data/data/com.termux/files/usr/bin/notice4/notice4_shown"
                dialog_msgbox "Boxvidra Emulator Native" \
                "Windows 10 Mode Theme (Red) Installed Successfully."
            fi
            ;;
        4)
            echo -n "Installing Windows 10 Purple Mode Theme . . ."
            wget -q --show-progress -O Windows.10.Theme.Pack.tar.xz https://github.com/Boxvidra/Boxvidra-Project/releases/download/Native-Themes/Windows.10.Theme.Pack.tar.xz
            tar -xf Windows.10.Theme.Pack.tar.xz
            cd 'Windows 10 Theme Pack'
            cp -r .icons /data/data/com.termux/files/home/
            cp -r .themes /data/data/com.termux/files/home/
            cp -r 'Accessories And Backgrounds' /data/data/com.termux/files/home
            cp Programs/* ~/Desktop
            cp -r 'Configs (Light And Dark, Red And Purple, Green And Yellow Modes)' /data/data/com.termux/files/usr/share
            tar -xf /data/data/com.termux/files/usr/share/'Configs (Light And Dark, Red And Purple, Green And Yellow Modes)'/'Purple Mode Config'/.config.tar.xz -C /data/data/com.termux/files/home
            cp Windows-10-Icons.tar.xz /data/data/com.termux/files/usr/share/icons
            tar -xf /data/data/com.termux/files/usr/share/icons/Windows-10-Icons.tar.xz -C /data/data/com.termux/files/usr/share/icons
            cd
            chmod 777 -R 'Windows 10 Theme Pack'
            rm -r 'Windows 10 Theme Pack'
            rm Windows.10.Theme.Pack.tar.xz
            rm /data/data/com.termux/files/usr/share/icons/Windows-10-Icons.tar.xz
            clear
            ## Installed Successfully Theme
            mkdir -p "/data/data/com.termux/files/usr/bin/notice4"
            if [ ! -e "/data/data/com.termux/files/usr/bin/notice4/notice4_shown" ]; then
                touch "/data/data/com.termux/files/usr/bin/notice4/notice4_shown"
                dialog_msgbox "Boxvidra Emulator Native" \
                "Windows 10 Mode Theme (Purple) Installed Successfully."
            fi
            ;;
        5)
            echo -n "Installing Windows 10 Green Mode Theme . . ."
            wget -q --show-progress -O Windows.10.Theme.Pack.tar.xz https://github.com/Boxvidra/Boxvidra-Project/releases/download/Native-Themes/Windows.10.Theme.Pack.tar.xz
            tar -xf Windows.10.Theme.Pack.tar.xz
            cd 'Windows 10 Theme Pack'
            cp -r .icons /data/data/com.termux/files/home/
            cp -r .themes /data/data/com.termux/files/home/
            cp -r 'Accessories And Backgrounds' /data/data/com.termux/files/home
            cp Programs/* ~/Desktop
            cp -r 'Configs (Light And Dark, Red And Purple, Green And Yellow Modes)' /data/data/com.termux/files/usr/share
            tar -xf /data/data/com.termux/files/usr/share/'Configs (Light And Dark, Red And Purple, Green And Yellow Modes)'/'Green Mode Config'/.config.tar.xz -C /data/data/com.termux/files/home
            cp Windows-10-Icons.tar.xz /data/data/com.termux/files/usr/share/icons
            tar -xf /data/data/com.termux/files/usr/share/icons/Windows-10-Icons.tar.xz -C /data/data/com.termux/files/usr/share/icons
            cd
            chmod 777 -R 'Windows 10 Theme Pack'
            rm -r 'Windows 10 Theme Pack'
            rm Windows.10.Theme.Pack.tar.xz
            rm /data/data/com.termux/files/usr/share/icons/Windows-10-Icons.tar.xz
            clear
            ## Installed Successfully Theme
            mkdir -p "/data/data/com.termux/files/usr/bin/notice4"
            if [ ! -e "/data/data/com.termux/files/usr/bin/notice4/notice4_shown" ]; then
                touch "/data/data/com.termux/files/usr/bin/notice4/notice4_shown"
                dialog_msgbox "Boxvidra Emulator Native" \
                "Windows 10 Mode Theme (Green) Installed Successfully."
            fi
            ;;
        6)
            echo -n "Installing Windows 10 Yellow Mode Theme . . ."
            wget -q --show-progress -O Windows.10.Theme.Pack.tar.xz https://github.com/Boxvidra/Boxvidra-Project/releases/download/Native-Themes/Windows.10.Theme.Pack.tar.xz
            tar -xf Windows.10.Theme.Pack.tar.xz
            cd 'Windows 10 Theme Pack'
            cp -r .icons /data/data/com.termux/files/home/
            cp -r .themes /data/data/com.termux/files/home/
            cp -r 'Accessories And Backgrounds' /data/data/com.termux/files/home
            cp Programs/* ~/Desktop
            cp -r 'Configs (Light And Dark, Red And Purple, Green And Yellow Modes)' /data/data/com.termux/files/usr/share
            tar -xf /data/data/com.termux/files/usr/share/'Configs (Light And Dark, Red And Purple, Green And Yellow Modes)'/'Yellow Mode Config'/.config.tar.xz -C /data/data/com.termux/files/home
            cp Windows-10-Icons.tar.xz /data/data/com.termux/files/usr/share/icons
            tar -xf /data/data/com.termux/files/usr/share/icons/Windows-10-Icons.tar.xz -C /data/data/com.termux/files/usr/share/icons
            cd
            chmod 777 -R 'Windows 10 Theme Pack'
            rm -r 'Windows 10 Theme Pack'
            rm Windows.10.Theme.Pack.tar.xz
            rm /data/data/com.termux/files/usr/share/icons/Windows-10-Icons.tar.xz
            clear
            ## Installed Successfully Theme
            mkdir -p "/data/data/com.termux/files/usr/bin/notice4"
            if [ ! -e "/data/data/com.termux/files/usr/bin/notice4/notice4_shown" ]; then
                touch "/data/data/com.termux/files/usr/bin/notice4/notice4_shown"
                dialog_msgbox "Boxvidra Emulator Native" \
                "Windows 10 Mode Theme (Yellow) Installed Successfully."
            fi
            ;;
    esac
    ;;
2)
    dialog_menu "\Z6Select A Theme To Install" "" \
    "1" "\Z6Windows 7 Theme" \
    "2" "\Z6Windows 95 Theme \Z5(Recommended)" \
    "3" "\Z6Windows 95 Theme"
    case $? in
        1)
   echo -n "Installing Windows 7 theme . . ."
      
   cd /data/data/com.termux/files/usr/share/icons
   git clone https://github.com/B00merang-Artwork/Windows-7.git
   cd
   wget -q --show-progress -O Windows.7.tar.xz https://github.com/Boxvidra/Boxvidra-Project/releases/download/Native-Themes/Windows.7.tar.xz
   tar -xf Windows.7.tar.xz
   cd 'Windows 7'
   cp -r .icons/* /data/data/com.termux/files/home/.icons
   cp -r .themes/* /data/data/com.termux/files/home/.themes
   cp -r .config /data/data/com.termux/files/home
   cp Programs/* ~/Desktop
   cp -r 'Accessories And Backgrounds' /data/data/com.termux/files/home
   rm -r 'Windows 7'
   rm Windows.7.tar.xz
   clear
## Installed Successfully Theme
    mkdir -p "/data/data/com.termux/files/usr/bin/notice4"
    if [ ! -e "/data/data/com.termux/files/usr/bin/notice4/notice4_shown" ]; then
	touch "/data/data/com.termux/files/usr/bin/notice4/notice4_shown"
	dialog_msgbox "Boxvidra Emulator Native" \
		"Windows 7 Theme Installed Successfully."
		    fi
            ;;
        2)
   echo -n "Installing Windows XP theme . . ."
   
   wget -q --show-progress -O Windows.XP.tar.xz https://github.com/Boxvidra/Boxvidra-Project/releases/download/Native-Themes/Windows.XP.tar.xz
   tar -xf Windows.XP.tar.xz
   cd 'WindowsXP'
   cp -r .icons /data/data/com.termux/files/home/
   cp -r .themes /data/data/com.termux/files/home/
   cp Programs/* ~/Desktop
   cp .config.tar.xz /data/data/com.termux/files/home
   tar -xf /data/data/com.termux/files/home/.config.tar.xz -C /data/data/com.termux/files/home
   cp Windows-XP-3.1.tar.xz /data/data/com.termux/files/usr/share/icons
   tar -xf /data/data/com.termux/files/usr/share/icons/Windows-XP-3.1.tar.xz -C /data/data/com.termux/files/usr/share/icons
   cp -r 'Accessories And Backgrounds' /data/data/com.termux/files/home
   rm /data/data/com.termux/files/home/.config.tar.xz
   cd ..
   rm -r 'WindowsXP'
   rm Windows.XP.tar.xz
   rm /data/data/com.termux/files/usr/share/icons/Windows-XP-3.1.tar.xz
   clear
## Installed Successfully Theme
    mkdir -p "/data/data/com.termux/files/usr/bin/notice5"
    if [ ! -e "/data/data/com.termux/files/usr/bin/notice5/notice5_shown" ]; then
	touch "/data/data/com.termux/files/usr/bin/notice5/notice6_shown"
	dialog_msgbox "Boxvidra Emulator Native" \
		"Windows XP Theme Installed Successfully."
		    fi
 		   ;; 
        3)
   echo -n "Installing Windows 95 theme . . ."

   wget -q --show-progress -O Windows.95.tar.xz https://github.com/Boxvidra/Boxvidra-Project/releases/download/Native-Themes/Windows.95.tar.xz
   tar -xf Windows.95.tar.xz
   cd 'Windows 95'
   cp -r .icons /data/data/com.termux/files/home/
   cp -r .themes /data/data/com.termux/files/home/
   cp PROGRAMS/* ~/Desktop
   cp .config.tar.xz /data/data/com.termux/files/home
   tar -xf /data/data/com.termux/files/home/.config.tar.xz -C /data/data/com.termux/files/home
   cp Chicago95.tar.xz /data/data/com.termux/files/usr/share/icons
   tar -xf /data/data/com.termux/files/usr/share/icons/Chicago95.tar.xz -C /data/data/com.termux/files/usr/share/icons
   cp -r WALLPAPER /data/data/com.termux/files/home
   rm /data/data/com.termux/files/home/.config.tar.xz
   cd ..
   rm -r 'Windows 95'
   rm Windows.95.tar.xz
   rm /data/data/com.termux/files/usr/share/icons/Chicago95.tar.xz
   clear
## Installed Successfully Theme
    mkdir -p "/data/data/com.termux/files/usr/bin/notice4"
    if [ ! -e "/data/data/com.termux/files/usr/bin/notice4/notice4_shown" ]; then
	touch "/data/data/com.termux/files/usr/bin/notice4/notice4_shown"
	dialog_msgbox "Boxvidra Emulator Native" \
		"Windows 95 Theme Installed Successfully."
		    fi
            ;;
    esac
    ;;
esac

## Apps Shortcuts (1/3)
dialog_menu "\Z6Select A Shortcut To Install (1/3)" "" \
            "1" "\Z6Facebook" \
            "2" "\Z6Youtube" \
            "3" "\Z6Instagram" \
            "4" "\Z6Telegram" \
            "5" "\Z6Wikipedia" \
            "6" "\Z6Spotify" \
            "7" "\Z6Roblox" \
            "8" "\Z6Rockstar Games" \
            "9" "\Z6WhatsApp"
            


download_and_extract() {
    app_name=$1
    wget -q --show-progress -O "$app_name.tar.xz" "https://github.com/Boxvidra/Boxvidra-Project/releases/download/Native-Apps-Shortcuts/$app_name.tar.xz"
    tar -xJf "/data/data/com.termux/files/home/$app_name.tar.xz" -C /data/data/com.termux/files/home
    cd "$app_name"
    mv "$app_name.desktop" ~/Desktop
    cd ..
    rm "$app_name.tar.xz"
}

case $? in
    1) download_and_extract "Facebook" ;;
    2) download_and_extract "YouTube" ;;
    3) download_and_extract "Instagram" ;;
    4) download_and_extract "Telegram" ;;
    5) download_and_extract "Wikipedia" ;;
    6) download_and_extract "Spotify" ;;
    7) download_and_extract "Roblox" ;;
    8) download_and_extract "Rockstar Games" ;;
    9) download_and_extract "WhatsApp" ;;
esac

## Apps Shortcuts (2/3)
dialog_menu "\Z6Select A Shortcut To Install (2/3)" "" \
            "1" "\Z6Facebook" \
            "2" "\Z6Youtube" \
            "3" "\Z6Instagram" \
            "4" "\Z6Telegram" \
            "5" "\Z6Wikipedia" \
            "6" "\Z6Spotify" \
            "7" "\Z6Roblox" \
            "8" "\Z6Rockstar Games" \
            "9" "\Z6WhatsApp"
            


download_and_extract() {
    app_name=$1
    wget -q --show-progress -O "$app_name.tar.xz" "https://github.com/Boxvidra/Boxvidra-Project/releases/download/Native-Apps-Shortcuts/$app_name.tar.xz"
    tar -xJf "/data/data/com.termux/files/home/$app_name.tar.xz" -C /data/data/com.termux/files/home
    cd "$app_name"
    mv "$app_name.desktop" ~/Desktop
    cd ..
    rm "$app_name.tar.xz"
}

case $? in
    1) download_and_extract "Facebook" ;;
    2) download_and_extract "YouTube" ;;
    3) download_and_extract "Instagram" ;;
    4) download_and_extract "Telegram" ;;
    5) download_and_extract "Wikipedia" ;;
    6) download_and_extract "Spotify" ;;
    7) download_and_extract "Roblox" ;;
    8) download_and_extract "Rockstar Games" ;;
    9) download_and_extract "WhatsApp" ;;
esac

## Apps Shortcuts (3/3)
dialog_menu "\Z6Select A Shortcut To Install (3/3)" "" \
            "1" "\Z6Facebook" \
            "2" "\Z6Youtube" \
            "3" "\Z6Instagram" \
            "4" "\Z6Telegram" \
            "5" "\Z6Wikipedia" \
            "6" "\Z6Spotify" \
            "7" "\Z6Roblox" \
            "8" "\Z6Rockstar Games" \
            "9" "\Z6WhatsApp"
            


download_and_extract() {
    app_name=$1
    wget -q --show-progress -O "$app_name.tar.xz" "https://github.com/Boxvidra/Boxvidra-Project/releases/download/Native-Apps-Shortcuts/$app_name.tar.xz"
    tar -xJf "/data/data/com.termux/files/home/$app_name.tar.xz" -C /data/data/com.termux/files/home
    cd "$app_name"
    mv "$app_name.desktop" ~/Desktop
    cd ..
    rm "$app_name.tar.xz"
}

case $? in
    1) download_and_extract "Facebook" ;;
    2) download_and_extract "YouTube" ;;
    3) download_and_extract "Instagram" ;;
    4) download_and_extract "Telegram" ;;
    5) download_and_extract "Wikipedia" ;;
    6) download_and_extract "Spotify" ;;
    7) download_and_extract "Roblox" ;;
    8) download_and_extract "Rockstar Games" ;;
    9) download_and_extract "WhatsApp" ;;
esac

## Customization Files Installation Notice 
clear
mkdir -p "/data/data/com.termux/files/usr/bin/notice55"
if [ ! -e "/data/data/com.termux/files/usr/bin/notice/notice55_shown" ]; then
	touch "/data/data/com.termux/files/usr/bin/notice/notice55_shown"
	dialog_msgbox "Boxvidra Project - Emulator (Native)" \
		"Progress Notice \nThe Customizations Files, Themes, Icon Packs Installation Process Is Completed Successfully, Now You're About To Install The UI Features And Native Applications (Wine Applications, External Applications, Etc..)"
fi
##

## Install The UI Features
   clear
   sleep 3
   echo -e "\e[32m[+] Installing Boxvidra Emulator - UI Features . . .\e[0m"
   cd /data/data/com.termux/files
   wget -q --show-progress -O Boxvidra-Tools.And.UI-Features.tar.xz https://github.com/Boxvidra/Boxvidra-Project/releases/download/Native-Tools/Boxvidra-Tools.And.UI-Features.tar.xz
   tar -xf Boxvidra-Tools.And.UI-Features.tar.xz
   rm Boxvidra-Tools.And.UI-Features.tar.xz
   cd /data/data/com.termux/files/usr/share
   wget -q --show-progress -O Boxvidra-Tools.And.UI-Features.Config.tar.xz https://github.com/Boxvidra/Boxvidra-Project/releases/download/Native-Tools/Boxvidra-Tools.And.UI-Features.Config.tar.xz
   tar -xf Boxvidra-Tools.And.UI-Features.Config.tar.xz
   rm Boxvidra-Tools.And.UI-Features.Config.tar.xz
   cp -r /data/data/com.termux/files/usr/share/'Boxvidra Tools And UI Features Config'/.config /data/data/com.termux/files/home
   echo -e "\n"
   echo -e "\e[32m[✓] Boxvidra Emulator - UI Features Installed Successfully.\e[0m"
   echo -e "\n"
   echo -e "\e[32m[+] Installing Boxvidra Emulator - Native Applications . . .\e[0m"
   cd /data/data/com.termux/files/usr/glibc/opt
   wget -q --show-progress -O Boxvidra-Applications.tar.xz https://github.com/Boxvidra/Boxvidra-Project/releases/download/Native-Tools/Boxvidra-Applications.tar.xz
   tar -xf Boxvidra-Applications.tar.xz
   mv Applications /data/data/com.termux/files/home
   rm Boxvidra-Applications.tar.xz
   echo -e "\e[32m[✓] Boxvidra Emulator - Native Applications Installed Successfully.\e[0m"
   sleep 2
   clear

## Clear Cache And Temp Files
   pkg autoremove &>/dev/null
   pkg remove &>/dev/null
   pkg clear &>/dev/null

## Install A Icon Pack And Profile (Boxvidra Project - Icon Pack And Profiles)
    dialog_menu "\Z6Select A Theme To Install" "" \
    "1" "\Z6Boxvidra Project - Full Icon Pack And Profiles \Z5(Full Version, Recommended)" \
    "2" "\Z6Boxvidra Project - Orange Icon Pack And Profile \Z5(New)" \
    "3" "\Z6Boxvidra Project - Red Icon Pack And Profile \Z5(New, Recommended)" \
    "4" "\Z6Boxvidra Project - Blue Icon Pack And Profile \Z5(New, Recommended)"
    case $? in
        1)
            echo -n "Installing Boxvidra Project Icon Pack (Full Version) . . ."
            cd /sdcard/Download
            mkdir Boxvidra
            cd Boxvidra
            wget -q --show-progress -O Boxvidra.Project.Icons.Full-Version.tar.xz https://github.com/Boxvidra/BOXVIDRA-PROJECT./releases/download/Boxvidra-Icon-Pack/Boxvidra.Project.Icons.Full-Version.tar.xz
            tar -xf Boxvidra.Project.Icons.Full-Version.tar.xz
            rm Boxvidra.Project.Icons.Full-Version.tar.xz
            cd
            clear
            ## Installed Successfully Theme
            mkdir -p "/data/data/com.termux/files/usr/bin/notice11"
            if [ ! -e "/data/data/com.termux/files/usr/bin/notice11/notice11_shown" ]; then
                touch "/data/data/com.termux/files/usr/bin/notice11/notice11_shown"
                dialog_msgbox "Boxvidra Emulator Native" \
                "Boxvidra Project Icon Pack (Full Version) Installed Successfully In the path (/sdcard/Download/Boxvidra), Import The Ipk And Ibp In Input Bridge Application"
            fi
            ;;
        2)
            echo -n "Installing Boxvidra Project Icon Pack (Orange) . . ."
            cd /sdcard/Download
            mkdir Boxvidra
            cd Boxvidra
            wget -q --show-progress -O Boxvidra.Project.Icons.Orange.tar.xz https://github.com/Boxvidra/BOXVIDRA-PROJECT./releases/download/Boxvidra-Icon-Pack/Boxvidra.Project.Icons.Orange.tar.xz
            tar -xf Boxvidra.Project.Icons.Orange.tar.xz
            rm Boxvidra.Project.Icons.Orange.tar.xz
            cd
            clear
            ## Installed Successfully Theme
            mkdir -p "/data/data/com.termux/files/usr/bin/notice11"
            if [ ! -e "/data/data/com.termux/files/usr/bin/notice11/notice11_shown" ]; then
                touch "/data/data/com.termux/files/usr/bin/notice11/notice11_shown"
                dialog_msgbox "Boxvidra Emulator Native" \
                "Boxvidra Project Icon Pack (Orange) Installed Successfully In the path (/sdcard/Download/Boxvidra), Import The Ipk And Ibp In Input Bridge Application"
            fi
            ;;
        3)
            echo -n "Installing Boxvidra Project Icon Pack (Red) . . ."
            cd /sdcard/Download
            mkdir Boxvidra
            cd Boxvidra
            wget -q --show-progress -O Boxvidra.Project.Icons.Red.tar.xz https://github.com/Boxvidra/BOXVIDRA-PROJECT./releases/download/Boxvidra-Icon-Pack/Boxvidra.Project.Icons.Red.tar.xz
            tar -xf Boxvidra.Project.Icons.Red.tar.xz
            rm Boxvidra.Project.Icons.Red.tar.xz
            cd
            clear
            ## Installed Successfully Theme
            mkdir -p "/data/data/com.termux/files/usr/bin/notice11"
            if [ ! -e "/data/data/com.termux/files/usr/bin/notice11/notice11_shown" ]; then
                touch "/data/data/com.termux/files/usr/bin/notice11/notice11_shown"
                dialog_msgbox "Boxvidra Emulator Native" \
                "Boxvidra Project Icon Pack (Red) Installed Successfully In the path (/sdcard/Download/Boxvidra), Import The Ipk And Ibp In Input Bridge Application"
            fi
            ;;
        4)
            echo -n "Installing Boxvidra Project Icon Pack (Blue) . . ."
            cd /sdcard/Download
            mkdir Boxvidra
            cd Boxvidra
            wget -q --show-progress -O Boxvidra.Project.Icons.Blue.tar.xz https://github.com/Boxvidra/BOXVIDRA-PROJECT./releases/download/Boxvidra-Icon-Pack/Boxvidra.Project.Icons.Blue.tar.xz
            tar -xf Boxvidra.Project.Icons.Blue.tar.xz
            rm Boxvidra.Project.Icons.Blue.tar.xz
            cd
            clear
            ## Installed Successfully Theme
            mkdir -p "/data/data/com.termux/files/usr/bin/notice11"
            if [ ! -e "/data/data/com.termux/files/usr/bin/notice11/notice11_shown" ]; then
                touch "/data/data/com.termux/files/usr/bin/notice11/notice11_shown"
                dialog_msgbox "Boxvidra Emulator Native" \
                "Boxvidra Project Icon Pack (Blue) Installed Successfully In the path (/sdcard/Download/Boxvidra), Import The Ipk And Ibp In Input Bridge Application"
                fi
    sleep 3
    ;;
*)
    return 1
    ;;
esac

## Give The Permissions
chmod +x /data/data/com.termux/files/usr/bin/*
chmod 777 /data/data/com.termux/files/usr/bin/*
chmod +x /data/data/com.termux/files/home/Applications/'External Applications'/*
chmod +x /data/data/com.termux/files/home/Applications/'Wine Applications'/*
chmod +x /data/data/com.termux/files/home/Applications/'Input Bridge (Controller)'/*

## Update Notice
dialog_msgbox "Boxvidra Emulator - Native Version Patch Notes" "\Z6v1.1.0 Update Features That Are Available:\Zn

1. \Z5Customizations And Themes:\Zn
   - \Z4Boxvidra Configuration Application New Customizations:\Zn
     • Boxvidra Configuration Application Light (Mode)
     • Boxvidra Configuration Application Dark (Mode)

2. \Z5D3D And Mesa Updates And Upgrades:\Zn
   - \Z4No Updates For D3D Or Mesa.\Zn

3. \Z5New Applications, Upgrades, And Improvements:\Zn
   - Upgrade and complete Boxvidra Configuration Application.
   - Add new applications in the \"Home/Applications\" folder:
     • Input Bridge (Controller)
     • TFM (File Explorer)
     • 7zip (File Archiver)
     • WinRAR (File Archiver)
     • WinAMP (MP3 Player)
     • NotePad ++ (Text Editor)
     • MS Paint (Microsoft Paint App)
     • WhatsApp Shortcut
     • Telegram Shortcut
   - New Sections :
     • Resume, Restart, Stop Boxvidra Emulator Section (After Starting The Emulator)
     • Termux | X:11 Settings (Resolution Settings)
     • About Boxvidra (Information Section)
   - New Upgraded Sections :
     • Upgrade (Patch Notes) Section
     • Upgrade (Start Boxvidra Emulator) Section
   - New Upgrades For Applications File
   - New Icons For Boxvidra Cfg, WineXF Manager, Wine Applications, External Applications, Input Bridge.
   - Upgrade Box64 and Box64 Glibc Scripts.
   - Upgrade Wow64 Glibc Scripts.
   - Upgrade the installation bash script.

\Z5Fixes:\Zn
1. Box64-86 and Wow64 scripts Received Some Fixes.
2. Boxvidra Configuration App Received Some Fixes.
3. WineXF Manager App Received Some Fixes.
"

## Done
mkdir -p "/data/data/com.termux/files/usr/bin/notice404"
if [ ! -e "/data/data/com.termux/files/usr/bin/notice404/notice404_shown" ]; then
    touch "/data/data/com.termux/files/usr/bin/notice10/notice404_shown"
    dialog_msgbox "Boxvidra Emulator Native" \
        "Boxvidra Emulator Native Installed Successfully, Type boxvidra [--start] or boxvidra-native [--start] To Run The Emulator, Use [vidra] To Run The Emulator Directly"
fi

## Clear Cache And Temp Files
   pkg autoremove &>/dev/null
   pkg remove &>/dev/null
   pkg clear &>/dev/null
   
case $? in
    0)
        ;;
    255)
        break
        ;;
esac

cd
restore-termux-style
clear
